### ISSUE TITLE
Can not navigator with arrow keys

### ISSUE THREAD

**Issue by aztack** [Araxeus/ls-interactive#8]
![image](https://user-images.githubusercontent.com/782871/168947768-4097493d-619c-4c51-bc3e-75a5e2aff1a4.png)

I tried zsh/bash/fish with iTerm2.app and Terminal.app. None of them works.

**Comment by Araxeus** [comment]
That's weird, this app uses https://github.com/mitsuhiko/dialoguer for the select prompt

Could you try a few things to help me pinpoint the origin of this?

* Does pressing <kbd>Enter</kbd> do anything? (since `..` is selected it should change directory the parent)

* Does running `ls-interactive` instead of `lsi.sh` script work?

* Does https://github.com/Araxeus/ls-interactive/releases/tag/v1.2.0 work for you maybe?

It looks like it's maybe not waiting for input, just printing the prompt and exiting which shouldn't happen...

**Comment by marcoil** [comment]
Same problem here on Ubuntu 20.04, both with gnome-terminal and Tilix. Arrow keys do work on the 1.2.0 release, but not Shift+Enter or Ctrl+Enter. Pressing those just goes into the directory just like pressing Enter without modifiers.

**Comment by Araxeus** [comment]
> Same problem here on Ubuntu 20.04, both with gnome-terminal and Tilix. Arrow keys do work on the 1.2.0 release, but not Shift+Enter or Ctrl+Enter. Pressing those just goes into the directory just like pressing Enter without modifiers.

This sounds like a problem with `lsi.sh`

Maybe it doesn't wait for the program to complete executing

Can you try running ls-interactive (v1.3.0) instead of lsi and see if it works?

**Comment by marcoil** [comment]
> Can you try running ls-interactive (v1.3.0) instead of lsi and see if it works?

Exactly the same bug, it's not even possible to exit with Esc, I have to ^C kill it.

**Comment by Araxeus** [comment]
> > Can you try running ls-interactive (v1.3.0) instead of lsi and see if it works?
> 
> Exactly the same bug, it's not even possible to exit with Esc, I have to ^C kill it.

Thank you, that helps understanding where it might be coming from

Since v1.2 works but v1.3 doesn't, It's probably about the new "Fuzzy select" feature

I will look into it.

If you have rust installed you *could* try forking the repo and in `utils.rs` change both instances of `FuzzySelect` to just `Select` and try running `cargo run`

It's hard for me to debug this, since I'm personally using windows and it works perfectly there :/

**Comment by marcoil** [comment]
> change both instances of `FuzzySelect` to just `Select` and try running `cargo run`

I just tried this but I got the same bug :( It looks like a terminal problem, as the codes I get on stdout (^[[B, ^[[A…) are uninterpreted terminal escape codes. Let me know if you need to test something else, although I'm not familiar with either Rust or terminal programming so I won't be of much help.

**Comment by Araxeus** [comment]
can you try changing the following in `Cargo.toml` (add branch)

```toml
[patch.crates-io]
dialoguer = { git = 'https://github.com/araxeus/dialoguer', branch = 'unix_fix' }
```

([Enabled 'raw mode'](https://github.com/Araxeus/dialoguer/commit/9ed0f06708bab97c26073b2d0389a98fe967b312) before capturing key, might help)

(also beware because this will disable ^C for now)

----

if this still doesn't work, I'll try to get a Linux laptop from a friend this weekend and see if I can fix this

**Comment by marcoil** [comment]
With the unix_fix branch the input issue is solved, at least for arrow keys and using Esc to exit \o/

There are still some issues, I can open new tickets or help you debug in this one:

- Shift+Enter and Ctrl+Enter are still just Enter.
- When entering a directory, the listing is shown indented (as in the attached shot) until you move the cursor, then it's shown correctly. This doesn't happen with the first directory, only when entering a new one.

![ls-interactive entering dir](https://user-images.githubusercontent.com/1692381/169233647-e1b585db-1dba-43d3-ab1b-263ca5b42dde.png)

**Comment by Araxeus** [comment]
> With the unix_fix branch the input issue is solved, at least for arrow keys and using Esc to exit \o/

Well I'm glad the original issue is fixed at least 😁

> - Shift+Enter and Ctrl+Enter are still just Enter

Did you try v1.3.0 and reverted to `FuzzySelect`?

> - When entering a directory, the listing is shown indented (as in the attached shot) until you move the cursor, then it's shown correctly. This doesn't happen with the first directory, only when entering a new one.
> 
> ![ls-interactive entering dir](https://user-images.githubusercontent.com/1692381/169233647-e1b585db-1dba-43d3-ab1b-263ca5b42dde.png)

I suspect this might be because raw mode is enabled, might have to disable it before # re-rendering the list

----

Also could you confirm that fuzzy select works? (If you type letters - it filters the current list)

Thanks a lot for your help !

**Comment by marcoil** [comment]
> Did you try v1.3.0 and reverted to `FuzzySelect`?

Right, sorry. I re-enabled FuzzySelect and it does work, although with the same indentation problem:
![ls-interactive fuzzy select](https://user-images.githubusercontent.com/1692381/169508059-66263438-9c6c-4d23-ab20-e6890951655d.png)

Thank you for the project, I really like the idea!

**Comment by Araxeus** [comment]
Got my hands on a Linux laptop and fixed most problems in #10 

(the installation setup on Linux/Mac changed too)

----

Sadly <kbd>Ctrl</kbd>+<kbd>Enter</kbd> still doesn't work 
but you can use <kbd>Alt</kbd>+<kbd>Enter</kbd>instead of <kbd>Shift</kbd>+<kbd>Enter</kbd>

this is a bug in crossterm, see https://github.com/crossterm-rs/crossterm/issues/669

**Comment by Araxeus** [comment]
@aztack @marcoil check out https://github.com/Araxeus/ls-interactive/releases/tag/v1.4.0 :)

installation method changed too: https://github.com/Araxeus/ls-interactive#linuxmac

**Comment by marcoil** [comment]
This is great, everything works on my end!

Well, except for actually changing into the directory at exit, as I'm using fish and not bash :P Supporting all the Linux variants can be somewhat difficult, so thanks for your efforts.

When I get a little time I'll try to provide zsh and fish alternatives.

**Comment by Araxeus** [comment]
I don't actually know how fish behaves, but I think with some slight syntax change it might work:
```fish
function lsi
    set -l output (ls-interactive "$argv")
    if [ -n "$output" ]
        cd "$output"
    end
end
```
if you put this `lsi` function inside `~/.config/fish/config.fish`  does it work?
(you could instead add it as an [autoloading function](https://fishshell.com/docs/current/tutorial.html#autoloading-functions) which seems to be the preferred way)

the function just needs to call `ls-interactive`, capture its output, and `CD` to the output if its not empty

and for Zsh you should be able to put the original function in `zshrc` or `zshenv`
(from what I know bash syntax should work in zsh?)

**Comment by marcoil** [comment]
I hadn't seen your last response, sorry. But I did make an equivalent fish function and put it in pull request #13, in case you want to merge it. Thanks again!
